In [1]:
import pandas as pd
import numpy as np
import ipywidgets as widgets
from IPython.display import display
import os

# 0. 데이터 불러오기

In [2]:
# Raw_data 추출

industry_url = 'https://github.com/DongwooChae/QuantifyPro/blob/master/KPD/00.%ED%91%9C%EC%A4%80%EC%82%B0%EC%97%85%EB%B6%84%EB%A5%98.xlsx?raw=true'
price_url = 'https://github.com/DongwooChae/QuantifyPro/blob/master/KPD/01_%EC%A3%BC%EA%B0%80.xlsx?raw=true'
value_per_stock_url = 'https://github.com/DongwooChae/QuantifyPro/blob/master/KPD/02_%EC%A3%BC%EB%8B%B9%EA%B0%80%EC%B9%98.xlsx?raw=true'
fsdata_url = 'https://github.com/DongwooChae/QuantifyPro/blob/master/KPD/03_%EC%9E%AC%EB%AC%B4%EB%8D%B0%EC%9D%B4%ED%84%B0.xlsx?raw=true'

industry = pd.read_excel(industry_url)
price = pd.read_excel(price_url)
value_per_stock = pd.read_excel(value_per_stock_url)
fsdata = pd.read_excel(fsdata_url)

In [68]:
price.head()

,Date,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,현대차,기아,셀트리온,KB금융,NAVER,...,투비소프트,키움제6호스팩,신한제10호스팩,교보15호스팩,에스케이증권제8호스팩,유진스팩9호,엠에프엠코리아,에스케이증권제10호스팩,엔에이치스팩25호,CNH
0,2024-12-30,53200,173900,348000,949000,212000,100700,187500,82900,198900,...,980,2105,2245,2085,2080,2125,161,2065,2090,109
1,2024-12-27,53700,174500,348000,934000,215000,100900,180400,85000,197700,...,972,2140,2245,2075,2075,2105,161,2050,2085,109
2,2024-12-26,53600,170100,344500,937000,217500,102900,182900,85500,199900,...,960,2185,2245,2065,2070,2090,161,2065,2090,109
3,2024-12-24,54400,168500,350000,938000,216500,100600,185670,86500,202500,...,968,2130,2245,2085,2080,2095,161,2065,2105,109
4,2024-12-23,53500,169600,359000,949000,215000,100900,185192,87000,201000,...,982,2105,2245,2080,2075,2125,161,2075,2115,109

# 1. 데이터 정제하기

## 1.1 인덱스 설정

In [3]:
value_per_stock.columns
value_per_stock.rename({'Unnamed: 0':'종목명'}, axis='columns', inplace=True)

industry.set_index('종목명', inplace=True)
value_per_stock.set_index('종목명', inplace=True)

## 1.2 자료형 변환(astype)

In [ ]:
industry.dtypes

In [46]:
industry['차입금/시총']

종목명
삼성전자              5.360686
SK하이닉스           20.487014
LG에너지솔루션         20.752277
삼성바이오로직스          1.436124
현대차             316.451003
                   ...
유진스팩9호           14.788807
THE MIDONG             NaN
키움제6호스팩          16.582273
에스케이증권제10호스팩     21.484342
엔에이치스팩25호         6.620996
Name: 차입금/시총, Length: 2514, dtype: float64

In [ ]:
# 산업군 키워드 입력하여 회사 추출하기
# industry.loc[industry['10차표준(세분류)'].str.contains('게임')].index

Index(['크래프톤', '넷마블', '엔씨소프트', '펄어비스', '카카오게임즈', '위메이드', '더블유게임즈', 'NHN',
       '컴투스', '웹젠', '네오위즈', '골프존', '데브시스터즈', '위메이드맥스', '조이시티', '고스트스튜디오',
       '스코넥', '위메이드플레이', '엠게임', '액토즈소프트', '미투온', '티쓰리', '한빛소프트', '모비릭스',
       '드래곤플라이', '애닉'],
      dtype='object', name='종목명')

In [ ]:
# value_per_stock.astype(float)

,EPS,SPS,BPS,지배주주지분(천원),매출액(직전4분기)(천원),지배주주순이익(직전4분기)(천원),총자본(천원),매출액(직전4분기)(천원).1,당기순이익(직전4분기)(천원),상장주식수 (보통)(주),자기주식수 (보통)(주),유통보통주식수
종목명,,,,,,,,,,,,
삼성전자,5401.484101,49327.690753,63356.403559,3.761522e+11,2.928626e+11,3.206906e+10,2.400720e+11,2.034128e+11,2.376802e+10,5.969783e+09,32700000.0,5.937083e+09
SK하이닉스,15138.627962,83785.462852,94769.932461,6.530015e+10,5.773143e+10,1.043110e+10,6.533151e+10,4.854264e+10,1.026153e+10,7.280024e+08,38963634.0,6.890387e+08
LG에너지솔루션,-1549.910256,116110.029915,86396.811966,2.021685e+10,2.716975e+10,-3.626790e+08,1.609196e+10,8.721096e+09,-6.405790e+08,2.340000e+08,0.0,2.340000e+08
삼성바이오로직스,14787.785010,61320.028567,148812.055695,1.059155e+10,4.364392e+09,1.052506e+09,9.016904e+09,3.374740e+09,1.066737e+09,7.117400e+07,0.0,7.117400e+07
현대차,60853.667837,830830.222335,494146.338750,1.012741e+11,1.702767e+11,1.247182e+10,6.651314e+10,7.941582e+10,9.196482e+09,2.094162e+08,4468561.0,2.049476e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
유진스팩9호,0.000000,0.000000,0.000000,NaN,NaN,NaN,7.153400e+06,0.000000e+00,1.923139e+05,3.460000e+06,0.0,3.460000e+06
엠에프엠코리아,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.327449e+07,4846284.0,3.842821e+07
에스케이증권제10호스팩,0.000000,0.000000,0.000000,NaN,NaN,NaN,6.518194e+06,0.000000e+00,8.106015e+04,3.310000e+06,0.0,3.310000e+06
엔에이치스팩25호,0.000000,0.000000,0.000000,NaN,NaN,NaN,5.795648e+06,0.000000e+00,1.464630e+05,3.020000e+06,0.0,3.020000e+06
CNH,-2688.362162,-1360.036850,283.791024,1.009117e+07,-4.836079e+07,-9.559396e+07,5.866317e+06,-8.376999e+07,-9.582139e+07,3.720000e+07,1641561.0,3.555844e+07

In [71]:
var1 = value_per_stock.loc[industry.loc[industry['10차표준(세분류)'].str.contains('게임')].index].round(0).iloc[:,0:3]
var2 = var1.sort_values(['EPS','SPS','BPS'], ascending=False)

In [72]:
var2

             EPS       SPS       BPS
종목명
크래프톤     17623.0   57779.0  137628.0
골프존      11113.0  109149.0   73629.0
더블유게임즈    8182.0   31835.0   50072.0
엔씨소프트     6404.0   81239.0  157359.0
웹젠        2215.0    7783.0   22347.0
액토즈소프트    1625.0    7949.0   22179.0
네오위즈      1554.0   19419.0   25371.0
고스트스튜디오   1325.0    6998.0   11764.0
데브시스터즈    1251.0   20722.0   15239.0
엠게임        979.0    4455.0    6375.0
넷마블        240.0   32713.0   63394.0
펄어비스       155.0    5391.0   12141.0
미투온        146.0    3284.0    4520.0
위메이드플레이     96.0   11524.0   20937.0
티쓰리         65.0     944.0    1658.0
조이시티        55.0    2190.0    1537.0
한빛소프트      -22.0    1187.0     521.0
위메이드맥스    -148.0    2200.0    2383.0
스코넥       -518.0     347.0    1471.0
애닉        -683.0    2507.0     147.0
모비릭스     -1247.0    6379.0    6732.0
드래곤플라이   -2026.0    2277.0    1311.0
카카오게임즈   -3048.0   11642.0   18072.0
NHN      -4031.0   75852.0   47854.0
컴투스      -4404.0   58133.0   96463.0
위메이드     -5719.0   19741.0    6983.0

In [ ]:
# 1) EPS가 양수인 데이터만 필터링
df_positive = var2[var2['EPS'] > 0]

# 2) 통계값 계산
mean_val = df_positive['EPS'].mean()              # 평균
q1 = df_positive['EPS'].quantile(0.25)            # 1분위
median_val = df_positive['EPS'].median()          # 중위값(=2분위)
q3 = df_positive['EPS'].quantile(0.75)            # 3분위
q4 = df_positive['EPS'].quantile(1.0)             # 4분위(최댓값)

In [87]:
print(f"표준산업분류에 게임이 포함된 기업의 수는 {len(var2)}개 입니다.")
print(f"그 중, 현재 이익을 실현하고 있어서 주당 이익이 양수의 값을 갖는 기업의 수는 {(var2['EPS']>0).sum()}개 입니다.")
print(f"EPS가 양수인 종목의 평균값은 {mean_val:.2f}입니다.")
print(f"EPS가 양수인 종목의 1분위(Q1)는 {q1:.2f}입니다.")
print(f"EPS가 양수인 종목의 중위값(2분위, Median)은 {median_val:.2f}입니다.")
print(f"EPS가 양수인 종목의 3분위(Q3)는 {q3:.2f}입니다.")
print(f"EPS가 양수인 종목의 4분위(최댓값)는 {q4:.2f}입니다.")

표준산업분류에 게임이 포함된 기업의 수는 26개 입니다.
그 중, 현재 이익을 실현하고 있어서 주당 이익이 양수의 값을 갖는 기업의 수는 16개 입니다.
EPS가 양수인 종목의 평균값은 3314.25입니다.
EPS가 양수인 종목의 1분위(Q1)는 152.75입니다.
EPS가 양수인 종목의 중위값(2분위, Median)은 1288.00입니다.
EPS가 양수인 종목의 3분위(Q3)는 3262.25입니다.
EPS가 양수인 종목의 4분위(최댓값)는 17623.00입니다.

In [43]:
industry.replace('N.A.', np.nan, inplace=True)
industry.replace('차입금오류', np.nan, inplace=True)

In [44]:
# industry.dtypes
industry.astype({'10차표준(세분류)':'str','10차표준(세세분류)':'str','거래소 업종':'str','거래소(시장)':'str','베타':'float','차입금/시총':'float'}).dtypes

Ticker                  object
Symbol                  object
종목명(Eng)                object
법인번호                     int64
10차표준(세분류)              object
10차표준(세세분류)             object
거래소 업종                  object
거래소(시장)                 object
매출액(직전4분기)             float64
영업이익                   float64
세전이익                   float64
자본총계                   float64
베타                     float64
차입금/시총                 float64
거래정지                    object
관리종목                    object
상장일자                     int64
주요상품                    object
한계세율                    object
홈페이지                    object
EV/EBITDA              float64
PBR                    float64
PSR                    float64
PER                    float64
3개년(2023~2026) CAGR     object
2020                   float64
2021                   float64
2022                   float64
2023                   float64
2024                   float64
2025                   float64
2026                   float64
2027                   float64
dtype: object

In [40]:
industry.dtypes

Ticker                  object
Symbol                  object
종목명(Eng)                object
법인번호                     int64
10차표준(세분류)              object
10차표준(세세분류)             object
거래소 업종                  object
거래소(시장)                 object
매출액(직전4분기)             float64
영업이익                   float64
세전이익                   float64
자본총계                   float64
베타                     float64
차입금/시총                 float64
거래정지                    object
관리종목                    object
상장일자                     int64
주요상품                    object
한계세율                    object
홈페이지                    object
EV/EBITDA              float64
PBR                    float64
PSR                    float64
PER                    float64
3개년(2023~2026) CAGR     object
2020                   float64
2021                   float64
2022                   float64
2023                   float64
2024                   float64
2025                   float64
2026                   float64
2027                   float64
dtype: object

In [ ]:
# value_per_stock.rename_axis('종목명',inplace=True)

In [ ]:
# value_per_stock.head()
industry.columns

In [ ]:
industry.iloc[1: 10,0: 8]

In [15]:
# industry['10차표준(세분류)'].unique()
# industry['10차표준(세분류)'].value_counts()
industry['10차표준(세분류)'].nunique()

342

In [16]:
industry.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2514 entries, 삼성전자 to 엔에이치스팩25호
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ticker               2514 non-null   object
 1   Symbol               2514 non-null   object
 2   종목명(Eng)             2514 non-null   object
 3   법인번호                 2514 non-null   int64
 4   10차표준(세분류)           2514 non-null   object
 5   10차표준(세세분류)          2514 non-null   object
 6   거래소 업종               2514 non-null   object
 7   거래소(시장)              2514 non-null   object
 8   매출액(직전4분기)           2514 non-null   float64
 9   영업이익                 2514 non-null   float64
 10  세전이익                 2514 non-null   float64
 11  자본총계                 2514 non-null   float64
 12  베타                   2514 non-null   object
 13  차입금/시총               2494 non-null   object
 14  거래정지                 2514 non-null   object
 15  관리종목                 2514 non-null   object
 16  상장일자                 2514 non-null   int64
 17  주요상품                 2468 non-null   object
 18  한계세율                 2514 non-null   object
 19  홈페이지                 2514 non-null   object
 20  EV/EBITDA            2047 non-null   float64
 21  PBR                  2506 non-null   float64
 22  PSR                  2514 non-null   float64
 23  PER                  1755 non-null   float64
 24  3개년(2023~2026) CAGR  2423 non-null   object
 25  2020                 2514 non-null   float64
 26  2021                 2514 non-null   float64
 27  2022                 2514 non-null   float64
 28  2023                 2514 non-null   float64
 29  2024                 2514 non-null   float64
 30  2025                 2514 non-null   float64
 31  2026                 2514 non-null   float64
 32  2027                 2514 non-null   float64
dtypes: float64(16), int64(2), object(15)
memory usage: 732.3+ KB

In [7]:
# "10차표준(세분류)" 열의 고유값 추출 후 정렬
unique_values = industry['10차표준(세분류)'].astype(str).unique()
try:
    sorted_values = sorted(unique_values, key=locale.strxfrm)
except Exception:
    sorted_values = sorted(unique_values)

In [8]:
# 정렬된 값을 사용하여 체크박스 생성
checkboxes = [widgets.Checkbox(value=False, description=val) for val in sorted_values]

# 1행당 5개씩 배치하기 위해 리스트를 분할하여 HBox에 담기
rows = []
row_length = 5
for i in range(0, len(checkboxes), row_length):
    row = widgets.HBox(checkboxes[i:i+row_length])
    rows.append(row)
checkbox_container = widgets.VBox(rows)

In [9]:
# 결과 출력용 위젯 생성
output = widgets.Output()

In [10]:
# 확인 버튼과 리셋 버튼 생성
confirm_button = widgets.Button(description='확인')
reset_button = widgets.Button(description='리셋')

In [11]:
def on_confirm_button_clicked(b):
    output.clear_output()  # 이전 출력 지우기
    # 체크된 항목의 설명(카테고리)을 가져옴
    selected_categories = [cb.description for cb in checkboxes if cb.value]
    
    with output:
        if not selected_categories:
            print("선택된 항목이 없습니다.")
        else:
            # 선택된 카테고리에 해당하는 종목명(인덱스) 수집
            selected_indices = []
            for cat in selected_categories:
                indices = industry[industry['10차표준(세분류)'].astype(str) == cat].index.tolist()
                selected_indices.extend(indices)
            selected_indices = list(set(selected_indices))
            
            # value_per_stock에서 해당 종목명의 EPS, SPS, BPS 열 가져오기
            try:
                selected_data = value_per_stock.loc[selected_indices, ['EPS', 'SPS', 'BPS']]
                display(selected_data)
            except Exception as e:
                print("데이터를 가져오는 도중 에러 발생:", e)

def on_reset_button_clicked(b):
    # 모든 체크박스 선택 해제
    for cb in checkboxes:
        cb.value = False
    output.clear_output()  # 출력창 초기화
    with output:
        print("체크박스가 초기화되었습니다. 선택 후 확인 버튼을 눌러주세요.")



# 중복 등록 방지: 기존 이벤트 핸들러 제거 후 등록
confirm_button.unobserve_all()
confirm_button.on_click(on_confirm_button_clicked)

reset_button.unobserve_all()
reset_button.on_click(on_reset_button_clicked)

In [12]:
# 버튼들을 포함하여 화면에 표시 (원하는 순서대로 배치)
display(checkbox_container, widgets.HBox([confirm_button, reset_button]), output)

VBox(children=(HBox(children=(Checkbox(value=False, description='1차 비철금속 제조업'), Checkbox(value=False, descript…

HBox(children=(Button(description='확인', style=ButtonStyle()), Button(description='리셋', style=ButtonStyle())))

Output()